version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.20.1-buster

    working_directory: ~/ci

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-node_modules-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-node_modules-{{ checksum "yarn.lock" }}

      - run: echo $FIREBASE_CONFIG | base64 --decode > src/config/firebaseConfig.json 

      - run: npm run build

      - run: node tools/uploadS3.js 

